name: Phoxy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.14034709800034761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.2973563876003027
  saturation: 0.364815711742267
  rhythmicContrast: 0.11709682689979672
purpose: []
